# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get Version
      run: bash ./tools/get_version.sh

    - name: Build assets
      uses: wangyoucao577/go-release-action@v1
      with:
        project_path: ./cmd
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: restrego
        md5sum: FALSE
        sha256sum: TRUE

  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Get Version
      run: bash ./tools/get_version.sh

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          lindex/rest-rego
        tags: |
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
        labels: |
          org.opencontainers.image.title=restrego
          org.opencontainers.image.description=Protect your REST API with Rego policies
          org.opencontainers.image.source=https://github.com/AB-Lindex/rest-rego
          org.opencontainers.image.url=https://github.com/AB-Lindex/rest-rego
          org.opencontainers.image.licenses=MIT

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_SECRET }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        sbom: true
        provenance: mode=max
        tags: ${{ steps.meta.outputs.tags }}