apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: demo
  template:
    metadata:
      labels:
        k8s-app: demo
    spec:
      containers:
        - name: main
          image: ninlil/http-https-echo
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 10000
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /ready
              port: 10000

        - name: sidecar
          image: lindex/rest-rego
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_PORT
              value: '10000'
            # JWT/OIDC authentication (recommended)
            - name: WELLKNOWN_OIDC
              value: 'https://login.microsoftonline.com/YOUR-TENANT-ID/v2.0/.well-known/openid-configuration'
            - name: JWT_AUDIENCES
              value: 'api://your-guard-app-id'
          ports:
            - containerPort: 8181
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8182
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8182
          volumeMounts:
            - name: policies
              mountPath: /policies

      serviceAccount: demo
      serviceAccountName: demo

      volumes:
        - name: policies
          configMap:
            name: demo-policies
